### PR TITLE
added kind plural to properties

### PR DESCRIPTION
**Pull request by xrajesh**
Signed-off-by: Xavier Dharmaiyan <xavier@redhat.com>

**Related Issue:**  stolostron/backlog#<ISSUE_NUMBER>

### CODE REVIEW

**Comment by SherinV** [comment]
Do we need to add kind_plural to Cluster resource too? https://github.com/stolostron/search-aggregator/blob/fd9189ac1b0503aff338b4e7030b60e500477b55/pkg/clustermgmt/clusterWatch.go#L201

Currently we use `managedclusterinfos` as resourcestring in Clusters. Wondering if we should add the same to cluster properties too?

**Review by SherinV — APPROVED** [review]

**Review by Anxhela21 — APPROVED** [review]
/lgtm
/hold

**Pull request merged**
