### PR TITLE
update packages

### PR DESCRIPTION
**Pull request by SherinV**
### Related Issue

https://issues.redhat.com/browse/ACM-0000

### Description of changes
- Update packages

### CODE REVIEW

**Review by jlpadilla — COMMENTED** [review]
/lgtm

@SherinV Were all these because the upgrade to go1.20? Checking to cherry-pick when updating previous releases.

**Comment by SherinV** [comment]
@jlpadilla Just updated to be ahead of CVE's, if packages get outdated. 
Can you check why the syncinformers test is failing? Thanks.

**Comment by SherinV** [comment]
Yes, the code changes were due to lint errors as we moved to go1.20

**Review by jlpadilla — APPROVED** [review]
/lgtm

**Review by jlpadilla — COMMENTED** [review]
/lgtm

**Pull request closed without merging**
