### PR TITLE
update org references to stolostron

### PR DESCRIPTION
**Pull request by SherinV**
Signed-off-by: Sherin Varughese <shvarugh@redhat.com>

**Related Issue:**  open-cluster-management/backlog#18729 and https://github.com/stolostron/backlog/issues/18938

### CODE REVIEW

**Comment by SherinV** [comment]
2.5.0-SNAPSHOT-2022-01-24-20-09-26 has a known issue - https://coreos.slack.com/archives/CSZLMKPS5/p1643146680278200?thread_ts=1643146043.277200&cid=CSZLMKPS5, which is why e2e is failing.

**Review by jlpadilla — APPROVED** [review]
/lgtm
/hold

**Pull request merged**
